### ISSUE TITLE
Max Gas Price Concern

### ISSUE THREAD

**Issue by KeithSSmith** [bounty0x/Bounty0xCrowdsale#10]
Looking at the KnownConstants.sol contract and the code for the Gas Limit and Gas Price I have a concern that the Gas Price (30 Gwei) will not be high enough based on current transactions and the https://www.ethgasstation.info/

The code is fine but the current minimum recommended Gwei is 41 and throughout the day has fluctuated between that and the mid 60's.  This is mainly traced back to Cryptokitties and the excessive amount of transactions the blockchain is having to process but could inadvertently lock out everyone or cause excessive delays because the contract won't accept anything higher than 30 Gwei and miners won't process transactions that are below 40.

**Comment by dnzdlklc** [comment]
Thanks for the suggestion, Keith. We'll be adjusting the Gas Price and limit closer to time of main sale and depending on Ethereum network state.
